[project]
name = "task2"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "langchain>=1.0.3",
    "langchain-groq>=1.0.0",
    "langchain-mcp-adapters>=0.1.12",
    "langgraph>=1.0.2",
    "mcp>=1.20.0",
]
